/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StrcProgressBar {
        /**
          * The current progress as number between 0.0 and 1.0 (equals 100%).
         */
        "progress": number;
    }
}
declare global {
    interface HTMLStrcProgressBarElement extends Components.StrcProgressBar, HTMLStencilElement {
    }
    var HTMLStrcProgressBarElement: {
        prototype: HTMLStrcProgressBarElement;
        new (): HTMLStrcProgressBarElement;
    };
    interface HTMLElementTagNameMap {
        "strc-progress-bar": HTMLStrcProgressBarElement;
    }
}
declare namespace LocalJSX {
    interface StrcProgressBar {
        /**
          * The current progress as number between 0.0 and 1.0 (equals 100%).
         */
        "progress"?: number;
    }
    interface IntrinsicElements {
        "strc-progress-bar": StrcProgressBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "strc-progress-bar": LocalJSX.StrcProgressBar & JSXBase.HTMLAttributes<HTMLStrcProgressBarElement>;
        }
    }
}
